In [1]:
import numpy as np #lib for array
import matplotlib.pyplot #library use for plot purposes 
import pandas as pd #lib use to import dataset
import seaborn as sns
from sklearn.datasets import dataset

ImportError: cannot import name 'dataset' from 'sklearn.datasets' (C:\Users\ADEYEMI ADEDEJI\anaconda3\lib\site-packages\sklearn\datasets\__init__.py)

In [4]:
dataset=pd.read_csv('/Users/ADEYEMI ADEDEJI/Desktop/Machine Learning/train.csv')

In [6]:
dataset.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [7]:
dataset?

In [8]:
# dataset.describe()
# dataset.columns
# sns.pairplot(dataset)
# sns.heatmap(dataset.corr()), annot =(True)
# bias= 100
# x,y, coef= dataset(n_features=1, bias = bias, random_state=42, coef= True)
# x.shape, y.shape
# plt.scatter(x,y)

In [9]:
# import three models to compare
from sklearn.linear_model import LinearRegression 
from sklearn.neural_network import MLPRegressor # multi layer perception/ deep learning 
from sklearn.ensemble import RandomForestRegressor 

# import training and splitting
from sklearn.model_selection import train_test_split

In [ ]:
# HOW TO INSTANTIATE THE MODELS
modelLR = LinearRegression()
modelNN= MLPRegressor ()
modelRF = RandomForestRegressor()